### ISSUE TITLE
Test the logdata-anomaly-miner with Debian Bullseye and Ubuntu 20.04

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#220]
In our development process we install python3-cerberus and python3-kafka with pip. Those packages exist in Debian Bullseye and ubuntu 20.04 in the repositories. We need to make sure that we can use those packages in order to deliver working debian packages. Therefore we must test the logdata-anomaly-miner if it works with the kafka and cerberus packages installed from the debian/ubuntu repositories.

If it works, we should also write a note in the README.md that we tested the aminer with those systems.

- [ ] Install logdata-anomaly-miner on Debian Bullseye without aminer-ansible but with python3-kafka and python3-cerberus from debian repository

- [ ] Test logdata-anomaly-miner on Debian Bullseye

- [ ] Install logdata-anomaly-miner on Ubuntu 20.04 without aminer-ansible but with python3-kafka and python3-cerberus from ubuntu repository

- [ ] Test logdata-anomaly-miner on Ubuntu 20.04

- [ ] Write a note in README.md

**Comment by dITySoftware** [comment]
Ubuntu 20.04.1 LTS - Python3.8:
- uninstalled kafka-python from pip
- uninstalled cerberus from pip
- installed cerberus with apt
- installed python3-kafka with apt
- uninstalled scipy from pip
- installed python3-scipy with apt
- created all needed links for the tests to run (see travis)
- changed email account to root instead of mail in unittest
- ./runUnittests.sh # no error occurred
- ./runAMinerDemo.sh demo/AMiner/demo-config.py # no error, NO IMPORT WARNING!
- ./runAMinerDemo.sh demo/AMiner/jsonConverterHandler-demo-config.py # no error, NO IMPORT WARNING!
- ./runAMinerDemo.sh demo/AMiner/template_config.py # no error, NO IMPORT WARNING!
- ./runAMinerDemo.sh demo/AMiner/demo-config.yml # no error, NO IMPORT WARNING!
- ./runAMinerIntegrationTest.sh aminerIntegrationTest.sh config.py # no error, NO IMPORT WARNING!
- ./runAMinerIntegrationTest.sh aminerIntegrationTest2.sh config21.py config22.py # no error, NO IMPORT WARNING!
- ./runCoverageTests.sh # no error, NO IMPORT WARNING!

Everything worked as inteded even after changing the packages! I will try these tests also in Travis with python3.6.

**Comment by dITySoftware** [comment]
# install sudo
apt install sudo # run this as root
nano /etc/sudoers # append user  ALL=(ALL) NOPASSWD:ALL

# install aminer
git clone https://github.com/ait-aecid/logdata-anomaly-miner.git
cd logdata-anomaly-miner/

# Debian Bullseye does not offer python3.6 by default. All packages have to be linked into the python3.6 directory for aminer-ansible to work.
sudo mkdir /usr/lib/python3.6
sudo mkdir /usr/lib/python3.6/site-packages
sudo ln -s /usr/local/lib/python3.8/dist-packages/cerberus /usr/lib/python3.6/site-packages/cerberus
sudo ln -s /usr/local/lib/python3.8/dist-packages/kafka /usr/lib/python3.6/site-packages/kafka
nano ./scripts/aminer_install.sh # change BRANCH to development
sudo ./scripts/aminer_install.sh
sudo apt-get install -y exim4 procps cpulimit mailutils curl default-jre # default-jre is needed for kafka
sudo pip3 install coverage
sudo cp $PWD/source/root/etc/aminer/conf-available/generic/ApacheAccessModel.py /etc/aminer/conf-enabled/ApacheAccessModel.py
ln -s $PWD/source/root/usr/lib/logdata-anomaly-miner/aminer $PWD/aecid-testsuite/aminer
ln -s $PWD/source/root/etc/aminer/template_config.py $PWD/aecid-testsuite/demo/AMiner/template_config.py
cd aecid-testsuite
sudo chmod +x runUnittests.sh
sudo chmod +x runAMinerDemo.sh
sudo chmod +x runAMinerIntegrationTest.sh
sudo chmod +x runCoverageTests.sh
sudo dpkg-reconfigure locales # install de_AT.UTF-8, en_GB.UTF-8 and change de_AT.UTF-8 to default
export TZ=de_AT.UTF-8 # here i am not sure what worked, but the timezone needs to be de_AT.UTF-8!
nano /home/user/logdata-anomaly-miner/aecid-testsuite/unit/events/DefaultMailNotificationEventHandlerTest.py # change mail_call = 'echo p | mail -u mail' -> change mail_call = 'echo p | mail -u user'
./runUnittests.sh # YamlConfigTest fails as this is currently WIP.
./runCoverageTests # YamlConfigTest fails as this is currently WIP.
./runAMinerDemo.sh demo/AMiner/demo-config.py # no errors
./runAMinerDemo.sh demo/AMiner/jsonConverterHandler-demo-config.py # no errors
./runAMinerDemo.sh demo/AMiner/template_config.py # no errors
./runAMinerIntegrationTest.sh aminerIntegrationTest.sh config.py # no errors
./runAMinerIntegrationTest.sh aminerIntegrationTest2.sh config21.py config22.py # no errors

**Comment by dITySoftware** [comment]
There seems to be no problems with dpkg packages in Ubuntu 20.04 and Debian Bullseye!
However Ubuntu 18.04, which is used by Travis, does have some issues, for example python3-cerberus does not exist in the repositories.

Is it possible to update Travis' Ubuntu to Ubuntu 20.04 and test the code again?

**Comment by dITySoftware** [comment]
We should also change the pip installation to dpkg when the system is Ubuntu 20.04.

**Comment by dITySoftware** [comment]
@whotwagner please comment on this.
