### ISSUE TITLE
Create script that executes GettingStarted and TryItOut of AMiner Wiki automatically as own travis job

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#308]

**Comment by landauermax** [comment]
A problem with this issue is that travis tests the development branch, while the wiki reflects the maser branch. There is no simple solution to solve this, unfortunately. We propose the following strategy: A 1:1 copy of the Wiki (getting started + try it out separately) is stored in a directory in the repo - for example, in the demo folder of the test suite. This "temporary" wiki reflects the development branch and has to be updated whenever new changes are introduced in the aminer that cause that the configurations in this temporary wiki fail when executed. Every time we do a release of a new aminer version, we copy this temporary file into the real wiki - we should add a release template where this task needs to be checked. Does that sound like a reasonable solution?

**Comment by dITySoftware** [comment]
> A problem with this issue is that travis tests the development branch, while the wiki reflects the maser branch. There is no simple solution to solve this, unfortunately. We propose the following strategy: A 1:1 copy of the Wiki (getting started + try it out separately) is stored in a directory in the repo - for example, in the demo folder of the test suite. This "temporary" wiki reflects the development branch and has to be updated whenever new changes are introduced in the aminer that cause that the configurations in this temporary wiki fail when executed. Every time we do a release of a new aminer version, we copy this temporary file into the real wiki - we should add a release template where this task needs to be checked. Does that sound like a reasonable solution?

Okay, currently exactly this is implemented in the Pull Request. Please ask @whotwagner to approve it.
