### ISSUE TITLE
Parsing logs with multiple log lines per log event

### ISSUE THREAD

**Issue by tschohanna** [ait-aecid/logdata-anomaly-miner#372]
I need to write a parsing model for an application which produces multiple log lines per log event.
Is this even possible with AMiner? And if so, what kind of structure must my parsing model have? 

e.g.
LENGTH: "349" 
SESSIONID:[5] "43464" 
ENTRYID:[1] "1" 
STATEMENT:[1] "1" 
USERID:[6] "DBSNMP" 
USERHOST:[7] "SHOBEEN" 
TERMINAL:[3] "MAU" 
ACTION:[3] "100" 
RETURNCODE:[1] "0"

**Comment by 4cti0nfi9ure** [comment]
Hi,

yes it is possible to use the AMiner for parsing and analyzing log events that consist of multiple lines. We have a small PoC implementation for verbose journald logs that are available in Json format and a PoC for another proprietary multiline log format from a Siemens device used in CPS. However, we have not included this functionalities into the official AMiner repository yet. To enable processing multiline log events, changes in the ByteStreamLineAtomizer are required. We will try to finalize the implementation on this feature in the beginning of 2021.

Could you also provide us further information on the specific log format you are dealing with, so that we can take these information into account. For example: 

- Do all of the fields occur in each log line?
- Do they always occur in the same order? (This is, for example, not the case for the verbose journald logs in Json format. In this case you need an adapted version of the RepeatedElementDataModelElement.)
- Is there any symbol or sequence of symbols that marks the end of the log event, such as a blank line, a specific type of bracket or combination such as a curly bracket and a semicolon ('};')?

Best wishes,
Markus

**Comment by tschohanna** [comment]
Hi, thank you for your answer.

Yes, all fields occur per log event (always in the same order), a blank line marks the end of the log event.

**Comment by landauermax** [comment]
Hi tschohanna,

as my colleague mentioned, it is necessary to do some tiny tweaks to the code for multi line log support. I therefore created a fork with the required changes to parse your data: https://github.com/landauermax/logdata-anomaly-miner/tree/feature_multiline

We will include support for multi line logs by default in a future release of the aminer to fix this issue, but for now, I hope that the forked repository is an acceptable solution.

I also created a parser for your data: https://github.com/landauermax/logdata-anomaly-miner/blob/feature_multiline/source/root/etc/aminer/conf-available/generic/MultilineParsingModel.py

Attached you can find a configuration for the aminer (config.py) that loads a sample file I created (multiline_log.txt). I also included the output I obtained (multiline_output.txt), which shows that the lines were successfully parsed (the ParserCount analysis component shows that 3 "lines" were parsed, which refers to the 3 blocks of lines from the input file). 

I hope this will help you to get everything running, get back to us if anything is not working.

[multiline.zip](https://github.com/ait-aecid/logdata-anomaly-miner/files/5727076/multiline.zip)

**Comment by landauermax** [comment]
@dITySoftware I think it would make sense to include this functionality as a parameter of the ByteStreamAtomizer that can also be set in the yaml config, e.g., 
EOL_String = "\n" by default that can be overwritten by the user, in this case, it would be EOL_String = "\n\n". Could you please prepare this as a pull request?

**Comment by tschohanna** [comment]
Hi @landauermax,

thank you! That helped me a lot.
