### ISSUE TITLE
Tabs in logs

### ISSUE THREAD

**Issue by tschohanna** [ait-aecid/logdata-anomaly-miner#390]
My log file contains tabulators (e.g. System name:\tTESTNAME). However, the byte strings in the parsing models cannot interpret these tabulators (\t):
FixedDataModelElement('fixed1', b'System name:\t'),

How can I make it possible for the tabs to be interpreted correctly?

**Comment by landauermax** [comment]
What is the message that you get? Is it a python error message? I would expect that tabulators should work.

**Comment by tschohanna** [comment]
That is the output that I get when I execute AMiner:

2021-01-11 12:39:39 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  {
  "DebugLog": [
    "Starting match update on b'System name:\\tTESTNAME'",
    "Removed b'System name:', remaining 4 bytes",
    "Shortest unmatched data was b'\\tTESTNAME",
    ""
  ],
  "LogData": {
    "RawLogData": [
      "System name:\tTESTNAME"
    ],
    "Timestamps": [
      1610368779.12
    ],
    "LogLinesCount": 1
  },
  "AnalysisComponent": {
    "AnalysisComponentIdentifier": null,
    "AnalysisComponentType": "VerboseUnparsedAtomHandler",
    "AnalysisComponentName": null,
    "Message": "Unparsed atom received",
    "PersistenceFileName": null
  }
}

**Comment by landauermax** [comment]
I tried it on random data and it should work. Are you sure you are editing the correct parser file and that you saved it before running the aminer? Is the parser file in /etc/aminer/conf-enabled or linked there?

To test this, change your line to something like FixedDataModelElement('fixed1', b'System'), and I think the aminer will still say "Removed b'System name:', which should not be possible since you just deleted the "name" part. This means that you are not editing the correct file. 

I did the following: At first I inserted a tabulator in a Apache Access log line and got a similar result as you do:
2021-01-11 13:07:51 Unparsed atom received
VerboseUnparsedAtomHandler: "None" (1 lines)
  Starting match update on b'192.168.10.190 - - [29/Feb/2020:14:00:17 +0000]\t"GET /kronolith/ HTTP/1.1" 200 3452 "-" "-"'
  Removed b'192.168.10.190', remaining 77 bytes
  Removed b' ', remaining 76 bytes
  Removed b'-', remaining 75 bytes
  Removed b' ', remaining 74 bytes
  Removed b'-', remaining 73 bytes
  Removed b' ', remaining 72 bytes
  Removed b'[29/Feb/2020:14:00:17 ', remaining 50 bytes
  Removed b'+', remaining 49 bytes
  Removed b'0000', remaining 45 bytes
  Removed b']', remaining 44 bytes
  Shortest unmatched data was b'\t"GET /kronolith/ HTTP/1.1" 200 3452 "-" "-"'
192.168.10.190 - - [29/Feb/2020:14:00:17 +0000]	"GET /kronolith/ HTTP/1.1" 200 3452 "-" "-"

Then I edited the parser to include a \t at the correct position:
FixedDataModelElement('sp3', b'\t"'),

After that, the aminer correctly parses that section of the log line, e.g., the Value detector shows all parsed parts of the log line:
2021-01-11 13:09:50 New value(s) detected
NewMatchPathValueDetector: "NewMatchPathValueDetector3" (1 lines)
  /accesslog: b'192.168.10.190 - - [29/Feb/2020:13:58:32 +0000]\t"GET /services/portal/ HTTP/1.1" 200 7499 "-" "-"'
  /accesslog/host: b'192.168.10.190'
  /accesslog/sp0: b' '
  /accesslog/ident: b'-'
  /accesslog/sp1: b' '
  /accesslog/user: b'-'
  /accesslog/sp2: b' '
  /accesslog/time_model: b'[29/Feb/2020:13:58:32 +0000]'
    /accesslog/time_model/time: 1582984712
    /accesslog/time_model/sign: 0
    /accesslog/time_model/tz: 0
    /accesslog/time_model/bracket: b']'
  /accesslog/sp3: b'\t"'
  /accesslog/method: 0
  /accesslog/sp4: b' '
  /accesslog/request: b'/services/portal/'
  /accesslog/sp5: b' HTTP/'
  /accesslog/version: b'1.1'
  /accesslog/sp6: b'" '
  /accesslog/status: 200
  /accesslog/sp7: b' '
  /accesslog/size: 7499
  /accesslog/sp8: b' "-" "'
  /accesslog/useragent: b'-'
  /accesslog/sp9: b'"'
{'/accesslog/status': 200}
b'192.168.10.190 - - [29/Feb/2020:13:58:32 +0000]\t"GET /services/portal/ HTTP/1.1" 200 7499 "-" "-"'

**Comment by tschohanna** [comment]
I found the mistake - the logline above could not be parsed correctly and this has had an effect on the one with the tab...
I just have one more question:
My log file always has a kind of header at the top, with the log lines below.
How can I define my parsing model that the header (with several lines) is at the top and my log events (with several lines) are below?
Many thanks in advance.

**Comment by landauermax** [comment]
I am glad you could solve the problem.

I assume your header is always the same. I would suggest to place a FirstMatchModelElement and put the existing SequenceModelElement inside it, along with a FixedModelElement that contains your header. In this case, if the current processed logs do not fit the SequenceModelElement, the alternative (containing the header) will be used.

This could look like this (I did not test this code):

model = FirstMatchModelElement('firstmatch', [
      FixedDataModelElement('header', b'<header first line>\n<header second line>\n<etc>'),
      SequenceModelElement('multiline', [
        FixedDataModelElement('length_str', b'LENGTH: "'),
        DecimalIntegerValueModelElement('length'),
        FixedDataModelElement('sessionid_str', b'"\nSESSIONID:['),
        DecimalIntegerValueModelElement('sessionid_id'),
        ...
])

Consider lines 261-279 in https://github.com/landauermax/logdata-anomaly-miner/blob/feature_multiline/source/root/etc/aminer/conf-available/ait-lds/SyslogParsingModel.py#L261 as an example.

**Comment by tschohanna** [comment]
Actually, my header is not always the same (contains current machine version etc.).
However, I tried your suggested code with a static header. My problem now is that the parser parses the first log event (with several lines) but then stops. Do you have any idea why this happens?

**Comment by landauermax** [comment]
If you header changes, you can always model it the same way you model the rest of the log data. So instead of the static header, you use another SequenceModelElement that contains a sequence of FixedModelElement and variable elements such as the DecimalIntegerModelElement.

Does the stopping behavior only occur when you add the static header? Are the events and the header still separated by \n\n?

Are you sure that the aminer only parses the first log event and not the last one? Try to start the aminer with the following flags: "aminer -f". This ensure that the aminer starts at the beginning of the log file.

Could you send me a sample of your log data with the header and the parser you implemented for it? I think then it is easier for me to help you.

**Comment by tschohanna** [comment]
Hi, here is my log data:
HEADER
TEST: [4]
FINISH HEADER

Mon Dec 23 21:32:10 2020 +00:00
LENGTH : '226'
ACTION :[72] 'select * from database;'
DATABASE USER:[1] 'root'

Mon Dec 23 21:32:11 2020 +00:00
LENGTH : '237'
ACTION :[72] 'select user from database;'
DATABASE USER:[1] 'root'

Mon Dec 23 21:32:12 2020 +00:00
LENGTH : '218'
ACTION :[72] 'select timestamp from database;'
DATABASE USER:[1] 'root'

And this is my parser:
def get_model():
14
15     alphabet = b'!"#$%&*+,-./=()0123456789 :;<>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
16     """Return the model."""
17     model = FirstMatchModelElement('firstmatch',[
18         SequenceModelElement('header', [
19             FixedDataModelElement('test', b'HEADER\n'),
20             FixedDataModelElement('test2', b'TEST: ['),
21             DecimalIntegerValueModelElement('header_id'),
22             FixedDataModelElement('test3', b']\n'),
23             FixedDataModelElement('test4', b'FINISH HEADER'),
24         ]),
25         SequenceModelElement('multiline', [
26             FixedWordlistDataModelElement('weekday', [b'Mon', b'Tue', b'Wed', b'Thu', b'Fri', b'Sat', b'Sun']),
27             DateTimeModelElement('time', b' %b %d %H:%M:%S %Y'),
28             FixedDataModelElement('plus', b' +'),
29             DecimalIntegerValueModelElement('tz'),
30             FixedDataModelElement('end', b':00\n'),
31
32             FixedDataModelElement('length_str', b'LENGTH : \''),
33             DecimalIntegerValueModelElement('length'),
34             FixedDataModelElement('end2', b'\'\n'),
35
36             FixedDataModelElement('action1', b'ACTION :['),
37             DecimalIntegerValueModelElement('action_id'),
38             FixedDataModelElement('action2', b'] \''),
39             VariableByteDataModelElement('action_content', alphabet),
40             FixedDataModelElement('action3', b'\'\n'),
41
42             FixedDataModelElement('database_user1', b'DATABASE USER:['),
43             DecimalIntegerValueModelElement('database_user_id'),
44             FixedDataModelElement('database_user2', b'] \''),
45             VariableByteDataModelElement('database_user_name', alphabet),
46             FixedDataModelElement('database_user3', b'\''),
47
48         ])
49     ])
50     return model

Many thanks for your effort.

**Comment by landauermax** [comment]
Thanks for the data. The first issue I noticed is that your parser has problems with quotes, for example, b''' is not valid, but should be b"'". Here is the parser I used where I fixed these issues, which occur in some lines:

```python
from aminer.parsing import DateTimeModelElement
from aminer.parsing import DecimalIntegerValueModelElement
from aminer.parsing import FixedDataModelElement
from aminer.parsing import SequenceModelElement
from aminer.parsing import VariableByteDataModelElement
from aminer.parsing import FixedWordlistDataModelElement
from aminer.parsing import FirstMatchModelElement

def get_model():

  alphabet = b'!"#$%&*+,-./=()0123456789 :;<>?@abcdefghijklmnopqrstuvwxyz[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  """Return the model."""
  model = FirstMatchModelElement('firstmatch',[
  SequenceModelElement('header', [
  FixedDataModelElement('test', b'HEADER\n'),
  FixedDataModelElement('test2', b'TEST: ['),
  DecimalIntegerValueModelElement('header_id'),
  FixedDataModelElement('test3', b']\n'),
  FixedDataModelElement('test4', b'FINISH HEADER'),
  ]),
  SequenceModelElement('multiline', [
  FixedWordlistDataModelElement('weekday', [b'Mon', b'Tue', b'Wed', b'Thu', b'Fri', b'Sat', b'Sun']),
  DateTimeModelElement('time', b' %b %d %H:%M:%S %Y'),
  FixedDataModelElement('plus', b' +'),
  DecimalIntegerValueModelElement('tz'),
  FixedDataModelElement('end', b':00\n'),

  FixedDataModelElement('length_str', b"LENGTH : '"),
  DecimalIntegerValueModelElement('length'),
  FixedDataModelElement('end2', b"'\n"),

  FixedDataModelElement('action1', b'ACTION :['),
  DecimalIntegerValueModelElement('action_id'),
  FixedDataModelElement('action2', b"] '"),
  VariableByteDataModelElement('action_content', alphabet),
  FixedDataModelElement('action3', b"'\n"),

  FixedDataModelElement('database_user1', b'DATABASE USER:['),
  DecimalIntegerValueModelElement('database_user_id'),
  FixedDataModelElement('database_user2', b"] '"),
  VariableByteDataModelElement('database_user_name', alphabet),
  FixedDataModelElement('database_user3', b"'"),

  ])
  ])
  return model
```

I recreated the case and for me it seems to work. Are you sure that the aminer stops after the first line? It may be that there is just no output, because no anomalies occur. A "normal" line does not generate any output, however, we can use the ParserCount to see how many lines were parsed. I used the following config, be aware that I the paths in the ParserCount are adapted to include the FirstMatchModelElement:

```yaml
AMinerUser: 'aminer'  # optional default: aminer
AMinerGroup: 'aminer' # optional default: aminer

LogResourceList:
        - 'file:///home/ubuntu/git_data.log'

Parser:
        - id: 'multilineModel'
          type: MultilineModel
          start: True
          name: 'multiline'

Input:
        verbose: True
        timestamp_paths:
          - ''

Analysis:
         - type: "ParserCount"
           paths:
            - '/firstmatch/multiline/length'
            - '/firstmatch/header/test'
           report_interval: 5
           reset_after_report_flag: True
           learn_mode: true

EventHandlers:
        - id: "stpe"
          json: true # optional default: false
          type: "StreamPrinterEventHandler"
```

When running, after 5 second I got the output from the ParserCount, which shows that 3 normal lines and 1 header line were parsed successfully:

```
Count report (1 lines)
  {
  "StatusInfo": {
    "/firstmatch/multiline/length": {
      "CurrentProcessedLines": 3,
      "TotalProcessedLines": 3
    },
    "/firstmatch/header/test": {
      "CurrentProcessedLines": 1,
      "TotalProcessedLines": 1
    }
  },
  "FromTime": 1610617031.263204,
  "ToTime": 1610617036.263223
}
```

If you want your lines to create more output, you could add detectors, for example, this detector will create an anomaly every time a new LENGTH value occurs:

```
Analysis:
         - type: "NewMatchPathValueDetector"
           paths: ['/firstmatch/multiline/length']
           learn_mode: false
```

**Comment by tschohanna** [comment]
Thank you very much for your help! Now it works for me.
