### ISSUE TITLE
YamlConfig: Make Verbose true by default

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/logdata-anomaly-miner#483]
In the "input"-section we should make the verbose flag true per default

**Comment by dITySoftware** [comment]
Why that? I think the normal case is to use the SimpleUnparsedAtomHandler. If we set verbose true by default, then the VerboseUnparsedAtomHandler is used by default. Is that intended by you?

**Comment by landauermax** [comment]
The issue is that it is extremely difficult to understand what caused the unparsed line when verbose is false, since the aminer only prints the whole line and not the place where it stopped parsing. It is like having an anomaly by the value detector and not showing the value that caused the anomaly. In all our deployments we used the verbose handler instead of the simple unparsed handler. We therefore decided that it should be the default case, because it will also help beginners to get started when they write their own parsers.
