### ISSUE TITLE
Support boolean values in json data

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#500]
I think it is not possible to use a Wordlist element with boolean values in the json, e.g., I would expect that the following parser config works.

- id: timedOutField
  type: FixedWordlistDataModelElement
  name: 'timed_out'
  args:
    - 'true'
    - 'false'

I think the reason is that boolean values are not in quotes, e.g.,

{"timed_out": false}

**Comment by landauermax** [comment]
Please also extend the tests to cover boolean values.

**Comment by dITySoftware** [comment]
Did you actually try it or do you just think that it will not work?
If you tried, can you post the config and data used?

In either way I will create a test for it.

**Comment by dITySoftware** [comment]
The ByteStreamLineAtomizer does not use the json module and does not parse the data to json. false is just interpreted as a normal string. 

It is not needed to use ' in yaml as the type is known to be string. This config also works:
- id: timedOutField
  type: FixedWordlistDataModelElement
  name: 'timed_out'
  args:
  - true
  - false

**Comment by landauermax** [comment]
Here is the config and data. I noticed it while preparing a use case, but maybe I made some other mistake that is not related to the boolean value.

[json_issue.zip](https://github.com/ait-aecid/logdata-anomaly-miner/files/6041733/json_issue.zip)

**Comment by dITySoftware** [comment]
I have copied the provided config and data and run the aminer without any problems. I have also tested it with the other data and other config you provided.
No problem occurred.

Maybe it was the decoding error I solved in PR #502.

I can not reproduce the error (any more?) and will close it now.

'false' and 'true' need to be defined in ' as otherwise they are really interpreted like booleans.
