### ISSUE TITLE
FixedWordlistDataModelElement wrong path in MatchElement

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#712]
The FixedWordlistDataModelElement currently only returns the current path + element_id. For example /model/abc. This leads to issues with for example the NewMatchPathValueDetector which does not save all values, but only the last one.

The solution should append the word_pos as last path element. For example /model/abc/1

**Comment by landauermax** [comment]
I do not understand why this is an issue. Having only the path to the model is fine for the value detector. If we append the word position to the path, then there will always be the same value in each of the /model/abc/<id> and we cannot apply the value detector to the fixedwordlistelement itself, but only one specific value of it.

Maybe this issue comes from a misunderstanding of lists in json, where we have the issue that we cannot use the value detector and others on specific entries of the lists. for example, for the input json log {"a": ["x", "y", "z"]} I want to be able to have the paths /model/a/0 = x, /model/a/1 = y, /model/a/2 = z.

**Comment by dITySoftware** [comment]
> I do not understand why this is an issue. Having only the path to the model is fine for the value detector. If we append the word position to the path, then there will always be the same value in each of the /model/abc/ and we cannot apply the value detector to the fixedwordlistelement itself, but only one specific value of it.
> 
> Maybe this issue comes from a misunderstanding of lists in json, where we have the issue that we cannot use the value detector and others on specific entries of the lists. for example, for the input json log {"a": ["x", "y", "z"]} I want to be able to have the paths /model/a/0 = x, /model/a/1 = y, /model/a/2 = z.

I think we have discussed this in a meeting on the 20th may.
The match_object of FixedWordlistDataModelElement is the word position. Therefor the value detector only saves the last word position. With this solution the NewMatchPathDetector is the best fitting analyzer to show the new values found.

**Comment by landauermax** [comment]
I do not remember the outcome of the meeting unfortunately. Anyway, I do not think it is a good solution to use the path detector to detect new values. It is not intuitive this way, it is not possible to design a specific detector to the elements but instead new values will always be reported as new paths, and it is not possible to use the values for combo detection (and many other detectors). 

Moreover, the issue with lists in json logs remains. It does not have to be the fixedwordlistelements used to process the lists, also with variablebyte elements and others it should be possible to access specific elements of the lists. Accordingly, this needs to be fixed in the JsonParsingElement and not in the fixed word list element.

**Comment by dITySoftware** [comment]
I will try to reproduce the error and post back on it.

**Comment by dITySoftware** [comment]
I could not reproduce the error. Everything seems to work as intended.

So should i close the issue and the pull request?

**Comment by landauermax** [comment]
Yes, I will create a new issue with more details.

**Comment by landauermax** [comment]
Yes, I will create a new issue with more details.
