### ISSUE TITLE
Create standard parsers from demo files

### ISSUE THREAD

**Issue by landauermax** [ait-aecid/logdata-anomaly-miner#722]
We are testing json logs with several parsers (https://github.com/ait-aecid/logdata-anomaly-miner/tree/main/aecid-testsuite/demo/aminerJsonInputDemo)

We could use these parsers as standard parsers (conf-available/generic) and in standard configs. However, the parsers have to be more general, i.e., right now they contain a lot of fixed elements or fixed word lists that are very specific to the test file - for a standard parser that should work in every case, these fields need to be replaced by variable byte elements or similar.

**Comment by dITySoftware** [comment]
There is data from AIT-LDS-v1_1 in logdata-anomaly-miner/aecid-testsuite/demo/aminerJsonInputDemo/json_logs/aminer.log which are not compatible with the current generic Aminer model, because the output changed. So this data will not work with the current model, but only with the specific one.

This is just a documentation note.

**Comment by dITySoftware** [comment]
After thinking about it does not make much sense to create a generic parser for elastic, because basically any data can be used to index an elasticsearch (I think that is the idea of it). So everything what is valid json could be elastic data..

Please comment if I am wrong. Skipping this one for now.

**Comment by dITySoftware** [comment]
Also skipping json-input-demo-config.yml.
So I will create new configs for Suricata (normal), Suricata (Eve), Journal, Wazuh and Windows Event Logs (not sure if there should be some split between the different types of windows logs..)
