### ISSUE TITLE
Error while Parsing formatting symbols

### ISSUE THREAD

**Issue by tfankhauser** [ait-aecid/logdata-anomaly-miner#755]
I have json logs from windows event viewer, which sometimes contain symbols like \n or \r.

In this example, the log line (see attached) includes a string with "\r\n\t\t". This somehow breaks the parser into breaking up the string and getting unparsed atoms after that. 
Used parser file is attached as well. 
[Symbol_Error.zip](https://github.com/ait-aecid/logdata-anomaly-miner/files/6637179/Symbol_Error.zip)

Thank you!

**Comment by dITySoftware** [comment]
Basically this error had nothing to do with the parsing of json. The problem was in the parsing of the "args" in YamlConfig.py. The input was read as b'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:;&%=+$,/?%#\\\\~()\\r\\n\\t ' instead of b'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.:;&%=+$,/?%#\~()\r\n\t '.

This could happen quite often as the strings have to be encoded before usage. There is no way to use the bytes class in yaml.
I have fixed this by replacing the wrong characters (for example \\r) with the right ones (\r) every time a string has to be encoded. This solution is not optimal, however it should work. It also is very hard to test..

**Comment by landauermax** [comment]
Thanks for resolving the problem. Yes, it is not optimal, but I think it is an acceptable solution for now.
