### ISSUE TITLE
JSON output value format

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#82]
Affectedvalues has inconsistent data types, e.g., int and string.
Timestamps are sometimes floats and sometimes int. Should be always float.

**Comment by dITySoftware** [comment]
AffectedValues is set specifically by the Detector's values. What is the expected way of setting these values?
Using the AMinerDemo i could not reproduce integer Timestamps. Could you provide me some examples?

**Comment by landauermax** [comment]
We got a request that the json values should all be strings to make parsing easier. Since this should not be dependent on the detector, we could do this in the output components.

For integer timestamps, I tried to parse this line:
Feb 29 00:09:01 mail-2 CRON[27153]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
with this parser model:
parsing_model = SequenceModelElement('model', [
                DateTimeModelElement('time', b'%b %d %H:%M:%S'),
                AnyByteDataModelElement('remainder')])
and a simple new path detector.
I got this json output:
"Timestamps": [
      1582934941
    ],
Note that default_timestamp_paths must be set correctly.

**Comment by dITySoftware** [comment]
I have tried to reproduce the timestamps issue, but i could not. Line 31 in the JsonConverterEventHandler sets the Timestamps.
log_data['Timestamps'] = [round(log_atom.atom_time, 2)]

My explanation is that if there are no values after the comma (xx.00) the value seems to be integer.
With round there is no way to print zeros after the comma. If it really is necessary, the values could be formatted strings.
I think it should not be that difficult to parse these values without the comma if they occur.

**Comment by dITySoftware** [comment]
Detectors with AffectedValues are:

- EnhancedNewMatchPathValueComboDetector
- MatchFilter
- MissingMatchPathValueDetector
- NewMatchIdValueComboDetector
- NewMatchPathValueComboDetector
- NewMatchPathValueDetector
- TimeCorrelationDetector
- WhitelistViolationDetector

Still problematic:
EnhancedNewMatchPathValueComboDetector: The current output looks like this:
"AffectedLogAtomValues": [
      {
        "MatchValueList": [
          "localhost",
          "34617"
        ],
        "TimeFirstOccurrence": 1595920887.345,
        "TimeLastOccurence": 1595920887.345,
        "NumberOfOccurences": 1
      }
    ],
How should is it expected to look like?
For the easiest way to parse the affectedValues it would be:
"AffectedLogAtomValues": [
      "localhost",
      "34617",
      "1595920887.345",
      "1595920887.345",
      "1"
    ],
What do you think about it?

The MissingMatchPathValueDetector does not work in the AMinerDemo. Please check what's wrong there.

**Comment by dITySoftware** [comment]
Fixed -> issue can be closed.
