### ISSUE TITLE
ApacheAccessModel and ApacheAccessParsingModel are very similar.

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#820]
Only the hostname / client_ip seem to be different.

The ApacheAccessModel also seems to be outdated, because it can not parse any referer or user agent.

I suggest changing the ApacheAccessModel to be able to parse the mentioned data and to offer a general parser with like get_general_model(hostname).
The ApacheAccessModel would call get_general_model(host_name_model). The ApacheAccessParsingModel would import get_general_model and call it with the "client_ip" FirstMatchModelElement.

@landauermax please tell me your opinion on this.

**Comment by landauermax** [comment]
As far as I know, the ApacheAccessParsingModel is more generic than the ApacheAccessModel, i.e., there is no line that can be parsed with the ApacheAccessModel that cannot be parsed with the ApacheAccessParsingModel. Therefore, we should replace the ApacheAccessModel with the ApacheAccessParsingModel. Since it is both a generic parser and a parser that is needed for processing the AIT-LDS, we can keep the same file in two locations.

Please make sure that the Getting-Started and try-it-outs also work with the changed model. I assume many paths have to be changed in the wiki.

**Comment by dITySoftware** [comment]
I would not duplicate the file as this is a source of error in the future. I would rather only have it in general, as it should be with all AIT-LDS parsers, which are actually general parsers.
Getting-Started is currently not running and try-it-out would throw an error if it does not work.

I do not have the rights to update the wiki.

**Comment by landauermax** [comment]
I think that none of the ait-lds parsers are generic parsers, even the ApacheAccessModel could be extended in the future. We only want to make sure that we provide a set of parsers for our own dataset, and put these in the ait-lds folder. When we have another dataset (AIT-LDSv2.0) we will update these parsers independent from the generic parsers. Other than that, there is no reason to touch the ait-lds parsers again (unless the aminer code requires updates, for this reason we need the test of the parsers). 

So the problem is not that the parser models are similar, it is just that in this case the generic parser is not generic enough.

**Comment by dITySoftware** [comment]
Ok, then there will be two versions and the names of the files stay the same as they are, so we do not break anything. I will just update the generic parser to work properly.

**Comment by landauermax** [comment]
Thanks!
